public class ExceptionHandlingExample {
    public static void main(String[] args) {
        int a = 10/0;
        // int a = 10;
        // int b = 1;  // this will cause an ArithmeticException when used as a divisor
        // int[] c = {1, 2, 3};
        // try {
        //     int result = a / b;  // this line throws ArithmeticException
        //     System.out.println("Result: " + result);
        //     System.out.println(c[3]);
        // } 
        // catch (ArithmeticException e) {
        //     // this block catches the ArithmeticException and handles it
        //     System.out.println("Error: Division by zero is not allowed.");
        //     System.out.println("Exception details: " + e.getMessage());
        // }
        // catch (Exception e) {
        //     // this block catches the ArithmeticException and handles it
        //     System.out.println("Exception caught!" + e.getMessage());
        // } 
        // finally {
        //     // this block will always be executed regardless of an exception
        //     System.out.println("Cleanup can go here.");
        // }

        // System.out.println("Program continues here...");
        // // ...
    }
}